export default [
  {
    code: 'QTM',
    name: 'Qtum',
    min_confirmations: 12,
    is_crypto: true,
    minimal_amount: '10.00000000',
    maximal_amount: '15000.00000000',
    is_base_of_enabled_pair: true,
    is_quote_of_enabled_pair: true,
    has_enabled_pairs: true,
    is_base_of_enabled_pair_for_test: true,
    is_quote_of_enabled_pair_for_test: true,
    has_enabled_pairs_for_test: true,
    withdrawal_fee: '0.00000000',
  },
  {
    code: 'ETH',
    name: 'ethereum',
    min_confirmations: 12,
    is_crypto: true,
    minimal_amount: '0.01000000',
    maximal_amount: '100.00000000',
    is_base_of_enabled_pair: true,
    is_quote_of_enabled_pair: true,
    has_enabled_pairs: true,
    is_base_of_enabled_pair_for_test: true,
    is_quote_of_enabled_pair_for_test: true,
    has_enabled_pairs_for_test: true,
    withdrawal_fee: '0.00500000',
  },
  {
    code: 'BNB',
    name: 'Binance Coin',
    min_confirmations: 12,
    is_crypto: true,
    minimal_amount: '3.00000000',
    maximal_amount: '200.00000000',
    is_base_of_enabled_pair: true,
    is_quote_of_enabled_pair: true,
    has_enabled_pairs: true,
    is_base_of_enabled_pair_for_test: true,
    is_quote_of_enabled_pair_for_test: true,
    has_enabled_pairs_for_test: true,
    withdrawal_fee: '0.30000000',
  },
  {
    code: 'USDT',
    name: 'tether',
    min_confirmations: 6,
    is_crypto: true,
    minimal_amount: '1.00000000',
    maximal_amount: '150.00000000',
    is_base_of_enabled_pair: true,
    is_quote_of_enabled_pair: true,
    has_enabled_pairs: true,
    is_base_of_enabled_pair_for_test: true,
    is_quote_of_enabled_pair_for_test: true,
    has_enabled_pairs_for_test: true,
    withdrawal_fee: '1.00000000',
  },
  {
    code: 'RNS',
    name: 'renos',
    min_confirmations: 4,
    is_crypto: true,
    minimal_amount: '1.00000000',
    maximal_amount: '10000.00000000',
    is_base_of_enabled_pair: true,
    is_quote_of_enabled_pair: true,
    has_enabled_pairs: true,
    is_base_of_enabled_pair_for_test: true,
    is_quote_of_enabled_pair_for_test: true,
    has_enabled_pairs_for_test: true,
    withdrawal_fee: '0.00000000',
  },
  {
    code: 'KCS',
    name: 'KuCoin Shares',
    min_confirmations: 12,
    is_crypto: true,
    minimal_amount: '20.00000000',
    maximal_amount: '650.00000000',
    is_base_of_enabled_pair: true,
    is_quote_of_enabled_pair: true,
    has_enabled_pairs: true,
    is_base_of_enabled_pair_for_test: true,
    is_quote_of_enabled_pair_for_test: true,
    has_enabled_pairs_for_test: true,
    withdrawal_fee: '1.20000000',
  },
  {
    code: 'BCH',
    name: 'bitcoin-cash',
    min_confirmations: 6,
    is_crypto: true,
    minimal_amount: '0.00500000',
    maximal_amount: '15.00000000',
    is_base_of_enabled_pair: true,
    is_quote_of_enabled_pair: true,
    has_enabled_pairs: true,
    is_base_of_enabled_pair_for_test: true,
    is_quote_of_enabled_pair_for_test: true,
    has_enabled_pairs_for_test: true,
    withdrawal_fee: '0.00250000',
  },
  {
    code: 'XMR',
    name: 'monero',
    min_confirmations: 10,
    is_crypto: true,
    minimal_amount: '0.10000000',
    maximal_amount: '15.00000000',
    is_base_of_enabled_pair: true,
    is_quote_of_enabled_pair: true,
    has_enabled_pairs: true,
    is_base_of_enabled_pair_for_test: true,
    is_quote_of_enabled_pair_for_test: true,
    has_enabled_pairs_for_test: true,
    withdrawal_fee: '0.01100000',
  },
  {
    code: 'USD',
    name: 'USD',
    min_confirmations: null,
    is_crypto: false,
    minimal_amount: '50.00000000',
    maximal_amount: '1000.00000000',
    is_base_of_enabled_pair: false,
    is_quote_of_enabled_pair: true,
    has_enabled_pairs: true,
    is_base_of_enabled_pair_for_test: false,
    is_quote_of_enabled_pair_for_test: true,
    has_enabled_pairs_for_test: true,
    withdrawal_fee: '0.00000000',
  },
  {
    code: 'XVG',
    name: 'verge',
    min_confirmations: 6,
    is_crypto: true,
    minimal_amount: '100.00000000',
    maximal_amount: '1200000.00000000',
    is_base_of_enabled_pair: true,
    is_quote_of_enabled_pair: false,
    has_enabled_pairs: true,
    is_base_of_enabled_pair_for_test: true,
    is_quote_of_enabled_pair_for_test: true,
    has_enabled_pairs_for_test: true,
    withdrawal_fee: '1.00000000',
  },
  {
    code: 'EUR',
    name: 'EUR',
    min_confirmations: null,
    is_crypto: false,
    minimal_amount: '50.00000000',
    maximal_amount: '800.00000000',
    is_base_of_enabled_pair: false,
    is_quote_of_enabled_pair: true,
    has_enabled_pairs: true,
    is_base_of_enabled_pair_for_test: false,
    is_quote_of_enabled_pair_for_test: true,
    has_enabled_pairs_for_test: true,
    withdrawal_fee: '0.00000000',
  },
  {
    code: 'GBP',
    name: 'GBP',
    min_confirmations: null,
    is_crypto: false,
    minimal_amount: '50.00000000',
    maximal_amount: '700.00000000',
    is_base_of_enabled_pair: false,
    is_quote_of_enabled_pair: true,
    has_enabled_pairs: true,
    is_base_of_enabled_pair_for_test: false,
    is_quote_of_enabled_pair_for_test: true,
    has_enabled_pairs_for_test: true,
    withdrawal_fee: '0.00000000',
  },
  {
    code: 'KNC',
    name: 'KyberNetwork',
    min_confirmations: 12,
    is_crypto: true,
    minimal_amount: '20.00000000',
    maximal_amount: '1000.00000000',
    is_base_of_enabled_pair: true,
    is_quote_of_enabled_pair: true,
    has_enabled_pairs: true,
    is_base_of_enabled_pair_for_test: true,
    is_quote_of_enabled_pair_for_test: true,
    has_enabled_pairs_for_test: true,
    withdrawal_fee: '2.70000000',
  },
  {
    code: 'GNT',
    name: 'Golem',
    min_confirmations: 12,
    is_crypto: true,
    minimal_amount: '10.00000000',
    maximal_amount: '15000.00000000',
    is_base_of_enabled_pair: true,
    is_quote_of_enabled_pair: true,
    has_enabled_pairs: true,
    is_base_of_enabled_pair_for_test: true,
    is_quote_of_enabled_pair_for_test: true,
    has_enabled_pairs_for_test: true,
    withdrawal_fee: '0.00000000',
  },
  {
    code: 'DOGE',
    name: 'doge',
    min_confirmations: 6,
    is_crypto: true,
    minimal_amount: '100.00000000',
    maximal_amount: '5000000.00000000',
    is_base_of_enabled_pair: true,
    is_quote_of_enabled_pair: false,
    has_enabled_pairs: true,
    is_base_of_enabled_pair_for_test: true,
    is_quote_of_enabled_pair_for_test: true,
    has_enabled_pairs_for_test: true,
    withdrawal_fee: '1.00000000',
  },
  {
    code: 'EOS',
    name: 'EOS',
    min_confirmations: 12,
    is_crypto: true,
    minimal_amount: '2.00000000',
    maximal_amount: '200.00000000',
    is_base_of_enabled_pair: false,
    is_quote_of_enabled_pair: true,
    has_enabled_pairs: true,
    is_base_of_enabled_pair_for_test: true,
    is_quote_of_enabled_pair_for_test: true,
    has_enabled_pairs_for_test: true,
    withdrawal_fee: '0.35000000',
  },
  {
    code: 'LTC',
    name: 'litecoin',
    min_confirmations: 6,
    is_crypto: true,
    minimal_amount: '0.02000000',
    maximal_amount: '300.00000000',
    is_base_of_enabled_pair: true,
    is_quote_of_enabled_pair: true,
    has_enabled_pairs: true,
    is_base_of_enabled_pair_for_test: true,
    is_quote_of_enabled_pair_for_test: true,
    has_enabled_pairs_for_test: true,
    withdrawal_fee: '0.01000000',
  },
  {
    code: 'BTC',
    name: 'bitcoin',
    min_confirmations: 2,
    is_crypto: true,
    minimal_amount: '0.00100000',
    maximal_amount: '5.00000000',
    is_base_of_enabled_pair: true,
    is_quote_of_enabled_pair: true,
    has_enabled_pairs: true,
    is_base_of_enabled_pair_for_test: true,
    is_quote_of_enabled_pair_for_test: true,
    has_enabled_pairs_for_test: true,
    withdrawal_fee: '0.00050000',
  },
  {
    code: 'BDG',
    name: 'BitDegree',
    min_confirmations: 12,
    is_crypto: true,
    minimal_amount: '150.00000000',
    maximal_amount: '20000.00000000',
    is_base_of_enabled_pair: true,
    is_quote_of_enabled_pair: false,
    has_enabled_pairs: true,
    is_base_of_enabled_pair_for_test: true,
    is_quote_of_enabled_pair_for_test: true,
    has_enabled_pairs_for_test: true,
    withdrawal_fee: '75.00000000',
  },
  {
    code: 'OMG',
    name: 'OmiseGo',
    min_confirmations: 12,
    is_crypto: true,
    minimal_amount: '2.00000000',
    maximal_amount: '200.00000000',
    is_base_of_enabled_pair: true,
    is_quote_of_enabled_pair: true,
    has_enabled_pairs: true,
    is_base_of_enabled_pair_for_test: true,
    is_quote_of_enabled_pair_for_test: true,
    has_enabled_pairs_for_test: true,
    withdrawal_fee: '0.45000000',
  },
  {
    code: 'NANO',
    name: 'nano',
    min_confirmations: 1,
    is_crypto: true,
    minimal_amount: '0.01000000',
    maximal_amount: '300.00000000',
    is_base_of_enabled_pair: true,
    is_quote_of_enabled_pair: false,
    has_enabled_pairs: true,
    is_base_of_enabled_pair_for_test: true,
    is_quote_of_enabled_pair_for_test: true,
    has_enabled_pairs_for_test: true,
    withdrawal_fee: '0.10000000',
  },
  {
    code: 'ZEC',
    name: 'zcash',
    min_confirmations: 2,
    is_crypto: true,
    minimal_amount: '0.01000000',
    maximal_amount: '20.00000000',
    is_base_of_enabled_pair: true,
    is_quote_of_enabled_pair: true,
    has_enabled_pairs: true,
    is_base_of_enabled_pair_for_test: true,
    is_quote_of_enabled_pair_for_test: true,
    has_enabled_pairs_for_test: true,
    withdrawal_fee: '0.00200000',
  },
];
