export default {
  EUR: {
    LTC: true,
    BTC: true,
    BDG: false,
    RNS: false,
    BCH: true,
    ZEC: true,
    XVG: true,
    NANO: true,
    EOS: false,
    DOGE: true,
    OMG: false,
    ETH: false,
    USDT: true,
  },
  BGN: { ETH: false, BTC: false, LTC: false, RNS: false },
  CAD: { ETH: false, BTC: false, RNS: false, LTC: false },
  USD: {
    BTC: true,
    BDG: false,
    RNS: false,
    LTC: true,
    BCH: true,
    XVG: true,
    ZEC: true,
    NANO: true,
    DOGE: true,
    EOS: false,
    OMG: false,
    ETH: false,
    USDT: true,
  },
  GBP: {
    LTC: true,
    BTC: true,
    OMG: false,
    BDG: false,
    RNS: false,
    ZEC: true,
    XVG: true,
    BCH: true,
    DOGE: true,
    EOS: false,
    NANO: true,
    ETH: false,
    USDT: true,
  },
  RUB: { BTC: false, ETH: false, LTC: false, RNS: false, BCH: false, XVG: false, DOGE: false },
  JPY: { BTC: false, LTC: false, ETH: false, DOGE: false, XVG: false, RNS: false, BCH: false },
  HRK: { BTC: false, LTC: false, RNS: false, ETH: false },
  CHF: { BTC: false, LTC: false, RNS: false, ETH: false },
  PLN: { BTC: false, LTC: false, ETH: false, RNS: false },
  RON: { BTC: false, ETH: false, LTC: false, RNS: false },
  DOGE: { ETH: false, LTC: true, XVG: true, BCH: true, ZEC: true, USDT: true, EOS: false, BTC: true, OMG: false, BDG: false, NANO: true },
  NZD: { ETH: false, LTC: false, BTC: false, RNS: false },
  CZK: { BTC: false, LTC: false, ETH: false, RNS: false },
  BDG: {
    ZEC: false,
    LTC: false,
    DOGE: false,
    BCH: false,
    XVG: false,
    BTC: false,
    USDT: false,
    OMG: false,
    EOS: false,
    NANO: false,
    ETH: false,
  },
  ETH: {
    BCH: false,
    ZEC: false,
    XVG: false,
    DOGE: false,
    LTC: false,
    BTC: false,
    NANO: false,
    USDT: false,
    OMG: false,
    EOS: false,
    BDG: false,
  },
  BTC: { USDT: true, XVG: true, BCH: true, EOS: false, LTC: true, DOGE: true, ETH: false, OMG: false, BDG: false, NANO: true, ZEC: true },
  AUD: { LTC: false, ETH: false, BTC: false, RNS: false },
  ZEC: { BDG: false, XVG: true, BCH: true, EOS: false, OMG: false, NANO: true, ETH: false, BTC: true, LTC: true, DOGE: true, USDT: true },
  LTC: { XVG: true, BCH: true, EOS: false, USDT: true, DOGE: true, BTC: true, OMG: false, BDG: false, ETH: false, NANO: true, ZEC: true },
  XVG: { BTC: true, LTC: true, DOGE: true, ZEC: true, USDT: true, EOS: false, OMG: false, BCH: true, BDG: false, NANO: true, ETH: false },
  DKK: { ETH: false, LTC: false, RNS: false, BTC: false },
  BCH: { BTC: true, LTC: true, DOGE: true, ZEC: true, XVG: true, USDT: true, OMG: false, EOS: false, BDG: false, NANO: true, ETH: false },
  HUF: { ETH: false, LTC: false, RNS: false, BTC: false },
  USDT: { BTC: true, LTC: true, OMG: false, XVG: true, BCH: true, DOGE: true, BDG: false, ETH: false, ZEC: true, NANO: true, EOS: false },
  ZAR: { BTC: false, LTC: false, RNS: false, ETH: false },
  EOS: {
    LTC: false,
    ZEC: false,
    BTC: false,
    DOGE: false,
    OMG: false,
    BDG: false,
    XVG: false,
    BCH: false,
    NANO: false,
    ETH: false,
    USDT: false,
  },
  BRL: { LTC: false, BTC: false, RNS: false, ETH: false },
  IDR: { LTC: false, BTC: false, RNS: false, ETH: false },
  ILS: { LTC: false, BTC: false, RNS: false, ETH: false },
  INR: { LTC: false, BTC: false, RNS: false, ETH: false },
  TRY: { LTC: false, RNS: false, ETH: false, BTC: false },
  KRW: { LTC: false, RNS: false, ETH: false, BTC: false },
  NOK: { RNS: false, LTC: false, ETH: false, BTC: false },
  SEK: { RNS: false, LTC: false, ETH: false, BTC: false },
  OMG: {
    ZEC: false,
    EOS: false,
    BDG: false,
    NANO: false,
    DOGE: false,
    XVG: false,
    BCH: false,
    BTC: false,
    LTC: false,
    ETH: false,
    USDT: false,
  },
  NANO: { ZEC: true, OMG: false, EOS: false, BDG: false, XVG: true, BCH: true, ETH: false, BTC: true, LTC: true, DOGE: true, USDT: true },
  PHP: { BTC: false, RNS: false, LTC: false, ETH: false },
  RNS: { LTC: false, BTC: false, ETH: false },
  THB: { RNS: false, LTC: false, ETH: false, BTC: false },
  MXN: { RNS: false, LTC: false, ETH: false, BTC: false },
  MYR: { RNS: false, LTC: false, ETH: false, BTC: false },
};
