const restrictedResidenceLocationsMap = {
    IS: { countryName: 'Iceland' },
    IL: { countryName: 'Israel' },
    MA: { countryName: 'Morocco' },
    DZ: { countryName: 'Algeria' },
    EC: { countryName: 'Ecuador' },
    BO: { countryName: 'Bolivia' },
    MK: { countryName: 'Macedonia' },
    EG: { countryName: 'Egypt' },
    SA: { countryName: 'Saudi Arabia' },
    IQ: { countryName: 'Iraq' },
    PK: { countryName: 'Pakistan' },
    NP: { countryName: 'Nepal' },
    BD: { countryName: 'Bangladesh' },
    CN: { countryName: 'China' },
    KG: { countryName: 'Kyrgyzstan' },
    BH: { countryName: 'Bahrain' },
    NA: { countryName: 'Namibia' },
    QA: { countryName: 'Qatar' },
    AF: { countryName: 'Afghanistan' },
    KP: { countryName: 'North Korea' },
    SY: { countryName: 'Syria' },
    IR: { countryName: 'Iran' },
    CU: { countryName: 'Cuba' },
    US: { countryName: 'USA' },
    GB: { countryName: 'United Kingdom' },
    UA: {
        countryName: 'Ukraine',
        prohibitedStates: [{ isoCode: '43', name: 'Crimea region of Ukraine' }],
    },
}

export default restrictedResidenceLocationsMap;